# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-10 21:42
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApp',
            fields=[
                ('app_name', models.CharField(max_length=100, unique=True)),
                ('app_code', api.models.UUIDField(blank=True, editable=False, max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100, null=True)),
                ('entity_id', models.CharField(max_length=50, null=True)),
                ('entity_type', models.CharField(max_length=50, null=True)),
                ('commented_at', models.DateTimeField(auto_now_add=True, null=False)),
                ('text', models.CharField(max_length=50, null=True)),
                ('meta', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
