# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-24 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clientapp_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
