# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-25 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170924_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100, null=True)),
                ('entity_id', models.CharField(max_length=50, null=True)),
                ('entity_type', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
