# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-25 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
